### PR TITLE
Support custom importers

### PR DESCRIPTION
**Pull request by Slava**
Add hooks for an option called `importer` - an object that implements `find` and `readFile` operations in a custom way to enable new import syntax defined by the plugin.

This is useful for better cross-package imports in frameworks and package systems, such as Meteor.

I am open to making improvements to the PR, adding docs, etc, if somebody gives me a sign off as "this is a good feature we want to merge to Stylus" by one of the maintainers.

### CODE REVIEW

**Comment by Panya** [comment]
It's good intention. But I think implementation could be improved. E.g. we could extract current logic of `importFile` to the default importer (`lib/importer.js`). Also I would like to see tests/docs.

**Comment by Slava** [comment]
Excuse me, I didn't find a file called `/lib/importer.js`, would you please clarify?

**Comment by Panya** [comment]
I mean it would be nice to extract this logic to a file that should be placed at `lib/importer.js`.

**Comment by Slava** [comment]
Gotcha, I will work on this later this week with tests and docs. Thanks, comrade.

**Pull request closed without merging**
