### PR TITLE
chore: Remove node v10 and v12 which are EOL

### PR DESCRIPTION
**Pull request by richardsimko**
**What**: Removed node v10 and v12 from test matrix according to the conversation here: https://github.com/stylus/stylus/pull/2818#issuecomment-1776646949

**Why**: Both 10 and 12 are EOL since 2.5 and 1.5 years respectively. Test cases are failing when trying to update `@adobe/css-tools` to a version that's not vulnerable.

**Checklist**:

- [ ] Documentation N/A
- [x] Unit Tests
- [x] Code complete
- [x] Changelog

### CODE REVIEW

**Comment by richardsimko** [comment]
Feel free to change the wording in the changelog, I'm not quite sure if you want it to say "dropped support" or simply that they're no longer being tested for? I suppose considering how few users are probably on these very old versions and that the project is in a version <1.0.0 it doesn't matter much.

**Comment by iChenLei** [comment]
Thank you.

**Comment by richardsimko** [comment]
@iChenLei Can I get an approve or a merge? :)

**Comment by iChenLei** [comment]
> @iChenLei Can I get an approve or a merge? :)

@richardsimko I will handle this PR over the weekend

**Comment by richardsimko** [comment]
Awesome, thank you!

**Review by iChenLei — APPROVED** [review]

**Pull request merged**
