### PR TITLE
Paths should be normalised

### PR DESCRIPTION
**Pull request by blake-newman**
Paths should be normalized for windows support. As paths in windows return a format of \images\test.jpg - this not being web safe.

### CODE REVIEW

**Comment by Panya** [comment]
`replace` is not needed for `extname` and `basename`.

**Comment by blake-newman** [comment]
That's a good point - was being too cautious

**Comment by Panya** [comment]
I already fixed it in your commit :)

**Comment by blake-newman** [comment]
Haha just noticed. :)

**Pull request merged**
