### PR TITLE
✨ @apply support

### PR DESCRIPTION
**Pull request by acidjazz**
I've been using this branch for a while now on some projects and have to say I haven't had issues anywhere else, I know I'm missing some unit testing and documentation and I'll be happy to get those PR'ed as well as soon as I get time, but so far this attempt at resolving #2335 has worked nicely.

### CODE REVIEW

**Comment by xdan** [comment]
Hi, can you add a few examples here https://github.com/stylus/stylus/blob/dev/test/cases/variables.styl 
with comment - // native variables
And here results https://github.com/stylus/stylus/blob/dev/test/cases/variables.css

**Comment by acidjazz** [comment]
@xdan you got it!

**Comment by xdan** [comment]
@acidjazz I did not find examples in tests

**Comment by acidjazz** [comment]
@xdan sorry as soon as I get time I'll add them and let you know

**Comment by acidjazz** [comment]
@xdan tests added and passed!

**Comment by acidjazz** [comment]
@xdan let me know if these examples suffice!

**Comment by hybridvision** [comment]
I've been using this branch too for a few months on a project and haven't had any problems at all. I have some quite complex mixins and loops in my styles and they work like a charm. It would be nice to have this in the core :)

**Comment by acidjazz** [comment]
@xdan let me know if theres anything else you need!

**Comment by acidjazz** [comment]
@xdan just another shameless bump hoping we can merge or progress with this feature

**Comment by acidjazz** [comment]
@xdan you just made my day!

**Pull request merged**
