### PR TITLE
Basic sourcemaps support

### PR DESCRIPTION
**Pull request by Panya**

### CODE REVIEW

**Comment by jenius** [comment]
Hey @kizu -- quick question. Thank you so much first of all for implementing this, it seems like it's something people really care about. I'm working on getting sourcemaps integrated into a variety of stylus pipelines that I help to manage (accord, roots, gulp-stylus, etc.), and am having a little trouble deciphering the output format, when you return the sourcemap as an object and not inline as a comment.

While the sourcemaps v3 spec that's linked gives a certain expected output (an object with `sources`, `mappings` etc defined), what stylus returns is a strange object containing a `lines` key with a bunch of objects with `line`, `column`, and `sourceLine` keys inside of it.

It seems like this format could potentially be used to do sourcemapping, but I don't know what it is, it definitely is not the v3 format that you guys specify, and it isn't able to be handled by [convert-source-map](). So I guess my questions are what is it, how can we deal with it and convert it into a normal format, and would it be possible to return it as a standard sourcemaps v3 object instead? Happy to help out with anything if I can as well!

**Comment by contra** [comment]
FYI gulp-stylus 2.0 has support for sourcemaps thanks to @jenius and @stevelacy

**Comment by jenius** [comment]
:tada: :confetti_ball:

**Comment by stevelacy** [comment]
:cake: :beers:

**Comment by cecilemuller** [comment]
:thumbsup: :tada:

**Pull request merged**
