### PR TITLE
Add 'Getting started' to readme

### PR DESCRIPTION
**Pull request by FranzSkuffka**
Responding to #2071

### CODE REVIEW

**Comment by Panya** [comment]
Hi, thanks for the PR. Just one thing before merging: why are you mentioning `gulp-accord` rather than more popular and specific `gulp-stylus`?

**Comment by FranzSkuffka** [comment]
Accord is the plugin I personally use by default, because of the following:
Even though there is no difference in the actual usage for stylus alone I mentioned this because one might want to use some other languages in their gulp tasks too. Once you add another language like coffeescript it is less complicated with accord than it is with using many language-specific gulp plugins.

If you think this is completely out of scope I will change the PR.

**Comment by Panya** [comment]
Yep, it would be better if you change `gulp-accord` to `gulp-stylus`.

**Comment by kizu** [comment]
Another option: rewrite in a way to use both (like “use gulp-stylus or gulp-accord”) :)

**Comment by Panya** [comment]
Thanks!

**Pull request merged**
