### PR TITLE
Add percentage function to built in functions

### PR DESCRIPTION
**Pull request by iDev0urer**
The percentage function will simply turn a given number into a percent. SASS has a similar function. I wrote tests for it which are passing.

### CODE REVIEW

**Comment by kizu** [comment]
Seems fine! It would be nice to allow this function to handle more cases:

1. `percentage(1 / 100px)` — when there is already a unit inside, the result won't make much sense. This can be fixed by changing the `+ '%'` with `unit(num * 100, '%')`.

2. When the result is already in percents, the function shouldn't do anything: `percentage(40%)` should return just `40%`.

If you'd like, you can intruduce those changes to this function in this PR, or we'll do it by ourselves when the time would come for the next release.

**Comment by iDev0urer** [comment]
Great idea, I actually just found out about the unit() function. Very handy. I'll get that changed and pushed quickly

**Comment by iDev0urer** [comment]
Ok looks like everything is good. I added a new test as well just to make sure everything is hunky-dory

**Comment by Panya** [comment]
Thanks!

**Pull request merged**
