### PR TITLE
docs: new stylus-lang.com

### LINKED ISSUE #23: The document site need upgrade
I think the document need to be re-organized. The current document is lack or organizing. I think we should consider chunk it into many sections. Also, a searchbox would be welcome for a document. We can use google cse, duckduckgo or yandex.

Btw, I would like to suggest the writing style for document. Using this one: https://css-tricks.com/words-avoid-educational-writing

### LINKED ISSUE #1242: New site for Stylus
I'm here to say, that I'm working on the new Stylus site.

Right now the engine is almost complete (**upd: it is complete and is in production**), when all the basic stuff would be there, I'll move the site to the engine, without touching the existent content and without changing the styles. Then we could begin the rewriting of the existent docs, adding new examples, redesigning everything etc. — the new engine would make it easy and fun.

Deadline for the first sneak-peak for the site is somewhere around the first two weeks of January (somewhat far, I know, but realistic)

Below is my vision of the site, feel free to discuss anything.
## Engine

Right now the site is hosted on GitHub pages — and that's ok. But it is not using any of the nice Jekyll features — everything is built locally and then just pushed to the gh-pages branch.

I'm working on a proper Jekyll-based engine for blogs and sites that could be used for Stylus' site perfectly.

It would able us automate a lot of things for the docs and make them usable, maintainable and just awesome.
## The data

Right now the docs are in a strange state. Most of them are stored in the `gh-pages` branch, some of them are duplicated in the `docs/` of the `master` branch, and they're not synced. People don't know where to commit the changes and how to build them. We need to have only one place where the docs are stored and it should be the main repo, so people could update the docs when they update the code in one PR.

So, as the docs would be stored in `master` branch, how would they go to the `gh-pages`? Using git submodules. GitHub Pages support them, so we could just write the docs near the code and them attach them to the submodule. This way `gh-pages` won't contain any docs and there would be only an engine.
## The docs themselves

Most of the docs are somewhat generated from the jsdoc, then there were a lot of changes right in the generated files, thn some docs are hand-written from scratch etc.

I'm against using jsdoc and other autogenerated ways for main docs, as it limits what we can do in them and makes it hard to find where to fix things.

So, there should be only hand-written docs, containing useful up-to-date examples, placed in the `.md` in the `master` branch.
## Examples

@panya recently updated the client version of Stylus — http://learnboost.github.io/stylus/try.html

This means we have an ability to use it everywhere in the docs, enhancing every and each example.

Of course, that would be done in a lazy way, so even without the script you could see the `before`/`after` code, but when the script would be loaded, you could edit the `before` part to see how the `after` changes.
## Design and styles

That is not the most important thing, but it would be nice to have a new simple, but nice design for the site, and there should be some nice Stylus code inside. While I'm thinking on doing everything by myself there, you could contribute to it when I'll ship the first initial version.
## What else?

Feel free to tell what you miss in the Stylus' docs and site!

### PR DESCRIPTION
**Pull request by iChenLei**
**What**:

Try to fix https://github.com/stylus/stylus/issues/1242 and fix https://github.com/stylus/stylus-lang.com/issues/23

**Why**:

Modern documentation website is required !!!

**How**:

Using `vitepress` and `netlify` deploy our documentation website

| Description | ScreenShot |
| :----: | :---: |
| HomePage |  |
| HomePage(dark) |  |
| [Algolia search](https://www.algolia.com/for-open-source/) |  |
| Syntax Hilght(before) |  |
| Syntax Hilght(after) |  |
| TOC Anchor |  |
| i18n |  |

| Display on mobile | HomePage(old) | HomePag(new) | SubPage(new) |
| :----: | :---: | :---: | :---: |
|  Compare |  |  |  |

**TODO List**:

- [x] Apply [alogia open source sponsor](https://docsearch.algolia.com/apply/)
- [x] Apply [netlify open source sponsor](https://www.netlify.com/legal/open-source-policy/)
- [x] Github Actions AutoDeploy Pipeline
- [ ]  [Codepen playground](https://blog.codepen.io/documentation/embedded-pens/) for stylus-lang.com
- [x]  [Runkit playground](https://runkit.com/docs/embed) for stylus-lang.com
- [x] [Google Analytics](https://analytics.google.com)
- [x] Looking for funding, github sponsor / opencollective or whatever (optional)

cc @corysimmons @futekov @groenroos @ota-meshi @ThisIsManta

### CODE REVIEW

**Comment by corysimmons** [comment]
I love this but I would keep the [new logo](https://stylus-lang.com/img/stylus-logo.svg).

**Comment by futekov** [comment]
Great work, lots of improvement.
I'm fine with both the new and the old logo.

**Comment by iChenLei** [comment]
Hi, All. Try https://stylus-docs.netlify.app , give me more feedback. Thanks

**Comment by groenroos** [comment]
The new site looks amazing, really good job on this! 🎉

The documentation navigation is a lot better - although I wonder if it could be improved even more by coming up with some sort of logical grouping of the different features (instead of one long flat list in no particular order), so it's easier to scan for what you need?

I also echo @corysimmons' sentiment, I think we should keep the newer logo.

I think we need to also tighten up some of the language on the front page - happy to help with this!

**Comment by ota-meshi** [comment]
The new site is really cool! Thank you for great job!

**Comment by iChenLei** [comment]
@corysimmons  Are you manage stylus-lang.com domain ? How can we use the new doc site ?

**Comment by corysimmons** [comment]
@iChenLei Sorry, no. I handed it off to @futekov a few years ago.

**Comment by corysimmons** [comment]
@iChenLei Good job! New site looks great 👏

**Comment by nazarepiedady** [comment]
@iChenLei, @corysimmons, @kizu, @ota-meshi, @Panya, @xdan, @pakastin 

I am working on the translation to Portuguese of the website but I am having
some errors during the deployment to Netlify. 

Could you give me some light on how to solve this?

Could you help me to fix those warnings? it bothers me a little to see them there.

Thanks.

```sh
4:11:14 AM: build-image version: 4c0c1cadee6a31c9bb8d824514030009c4c05c6a (focal)
4:11:14 AM: build-image tag: v4.15.0
4:11:14 AM: buildbot version: 9ef4dba9386902658d5cc7ad8ca0406443896076
4:11:15 AM: Fetching cached dependencies
4:11:15 AM: Failed to fetch cache, continuing with build
4:11:15 AM: Starting to prepare the repo for build
4:11:15 AM: No cached dependencies found. Cloning fresh repo
4:11:15 AM: git clone https://github.com/nazarepiedady/stylus-docs-pt
4:11:15 AM: Preparing Git Reference refs/heads/main
4:11:16 AM: Parsing package.json dependencies
4:11:17 AM: Different build dir detected, going to use the one specified in the Netlify configuration file: 'docs' versus 'docs/' in the Netlify UI
4:11:17 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'docs/.vitepress/dist' versus '.vitepress/dist' in the Netlify UI
4:11:17 AM: Section completed: initializing
4:11:17 AM: Starting build script
4:11:17 AM: Installing dependencies
4:11:17 AM: Python version set to 2.7
4:11:17 AM: v16.18.1 is already installed.
4:11:18 AM: Now using node v16.18.1 (npm v8.19.2)
4:11:18 AM: Enabling node corepack
4:11:18 AM: Started restoring cached build plugins
4:11:18 AM: Finished restoring cached build plugins
4:11:18 AM: Attempting ruby version 2.7.2, read from environment
4:11:18 AM: Using ruby version 2.7.2
4:11:18 AM: Using PHP version 8.0
4:11:19 AM: No npm workspaces detected
4:11:19 AM: Started restoring cached node modules
4:11:19 AM: Finished restoring cached node modules
4:11:19 AM: Installing NPM modules using NPM version 8.19.2
4:11:41 AM: npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
4:11:41 AM: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
4:11:43 AM: added 574 packages, and audited 575 packages in 24s
4:11:43 AM: 98 packages are looking for funding
4:11:43 AM:   run `npm fund` for details
4:11:43 AM: found 0 vulnerabilities
4:11:43 AM: NPM modules installed
4:11:43 AM: Creating package sha
4:11:43 AM: Started restoring cached go cache
4:11:43 AM: Finished restoring cached go cache
4:11:45 AM: Installing Go version 1.19.3 (requested 1.19.x)
4:11:50 AM: unset GOOS;
4:11:50 AM: unset GOARCH;
4:11:50 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.19.3.linux.amd64';
4:11:50 AM: export PATH="/opt/buildhome/.gimme/versions/go1.19.3.linux.amd64/bin:${PATH}";
4:11:50 AM: go version >&2;
4:11:50 AM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.19.3.linux.amd64.env"
4:11:50 AM: go version go1.19.3 linux/amd64
4:11:50 AM: Detected 0 framework(s)
4:11:50 AM: Installing missing commands
4:11:50 AM: Verify run directory
4:11:51 AM: ​
4:11:51 AM: ────────────────────────────────────────────────────────────────
4:11:51 AM:   Netlify Build                                                 
4:11:51 AM: ────────────────────────────────────────────────────────────────
4:11:51 AM: ​
4:11:51 AM: ❯ Version
4:11:51 AM:   @netlify/build 28.4.4
4:11:51 AM: ​
4:11:51 AM: ❯ Flags
4:11:51 AM:   baseRelDir: true
4:11:51 AM:   buildId: 638d61481c52d8229f600afd
4:11:51 AM:   deployId: 638d61481c52d8229f600aff
4:11:51 AM: ​
4:11:51 AM: ❯ Current directory
4:11:51 AM:   /opt/build/repo/docs
4:11:51 AM: ​
4:11:51 AM: ❯ Config file
4:11:51 AM:   No config file was defined: using default values.
4:11:51 AM: ​
4:11:51 AM: ❯ Context
4:11:51 AM:   production
4:11:51 AM: ​
4:11:51 AM: ────────────────────────────────────────────────────────────────
4:11:51 AM:   1. Build command from Netlify app                             
4:11:51 AM: ────────────────────────────────────────────────────────────────
4:11:51 AM: ​
4:11:51 AM: $ npm run build
4:11:51 AM: > build
4:11:51 AM: > vitepress build
4:11:51 AM: vitepress v1.0.0-alpha.29
4:11:52 AM: - building client + server bundles...
4:12:06 AM: warnings
4:12:06 AM:   One of the glob patterns doesn't match any files. Please remove or fix the following: {  "globDirectory": "/opt/build/repo/docs/.vitepress/dist",
4:12:06 AM:   "globPattern": "**/*.{js,css,html}",
4:12:06 AM:   "globIgnores": [
4:12:06 AM:     "**/node_modules/**/*",
4:12:06 AM:     "sw.js",
4:12:06 AM:     "workbox-*.js"
4:12:06 AM:   ]
4:12:06 AM: }
4:12:06 AM: 
4:12:08 AM: warnings
4:12:08 AM:   One of the glob patterns doesn't match any files. Please remove or fix the following: {  "globDirectory": "/opt/build/repo/docs/.vitepress/dist",
4:12:08 AM:   "globPattern": "**/*.{js,css,html}",
4:12:08 AM:   "globIgnores": [
4:12:08 AM:     "**/node_modules/**/*",
4:12:08 AM:     "sw.js",
4:12:08 AM:     "workbox-*.js"
4:12:08 AM:   ]
4:12:08 AM: }
4:12:08 AM: 
4:12:11 AM: ✓ building client + server bundles...
4:12:11 AM: - rendering pages...
4:12:11 AM: ✖ rendering pages...
4:12:11 AM: build error:
4:12:11 AM:  TypeError: Cannot read properties of undefined (reading 'replace')
4:12:11 AM:     at ReactiveEffect.fn (file:///opt/build/repo/docs/.vitepress/.temp/app.js:2934:25)
4:12:11 AM:     at ReactiveEffect.run (/opt/build/repo/docs/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:159:25)
4:12:11 AM:     at ComputedRefImpl.get value [as value] (/opt/build/repo/docs/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:1072:39)
4:12:11 AM:     at unref (/opt/build/repo/docs/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:981:29)
4:12:11 AM:     at file:///opt/build/repo/docs/.vitepress/.temp/app.js:3019:21
4:12:11 AM:     at renderComponentSubTree (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)
4:12:11 AM:     at renderComponentVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
4:12:11 AM:     at ssrRenderComponent (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
4:12:11 AM:     at file:///opt/build/repo/docs/.vitepress/.temp/app.js:3170:13
4:12:11 AM:     at renderComponentSubTree (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)
4:12:11 AM:     at renderComponentVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
4:12:11 AM:     at ssrRenderComponent (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
4:12:11 AM:     at file:///opt/build/repo/docs/.vitepress/.temp/app.js:3245:15
4:12:11 AM:     at renderComponentSubTree (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)
4:12:11 AM:     at renderComponentVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
4:12:11 AM:     at ssrRenderComponent (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
4:12:11 AM:     at file:///opt/build/repo/docs/.vitepress/.temp/app.js:3485:15
4:12:11 AM:     at renderComponentSubTree (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)
4:12:11 AM:     at renderComponentVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
4:12:11 AM:     at renderVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:296:22)
4:12:11 AM:     at renderComponentSubTree (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:202:9)
4:12:11 AM:     at renderComponentVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
4:12:11 AM:     at renderVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:296:22)
4:12:11 AM:     at renderComponentSubTree (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:260:13)
4:12:11 AM:     at renderComponentVNode (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
4:12:11 AM:     at renderToString (/opt/build/repo/docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:447:26)
4:12:11 AM:     at render (file:///opt/build/repo/docs/.vitepress/.temp/app.js:4337:10)
4:12:11 AM:     at async renderPage (file:///opt/build/repo/docs/node_modules/vitepress/dist/node/serve-fcdc8868.js:41266:19)
4:12:11 AM:     at async Promise.all (index 1)
4:12:11 AM:     at async build (file:///opt/build/repo/docs/node_modules/vitepress/dist/node/serve-fcdc8868.js:42017:7)
4:12:11 AM: ​
4:12:11 AM: ────────────────────────────────────────────────────────────────
4:12:11 AM:   "build.command" failed                                        
4:12:11 AM: ────────────────────────────────────────────────────────────────
4:12:11 AM: ​
4:12:11 AM:   Error message
4:12:11 AM:   Command failed with exit code 1: npm run build
4:12:11 AM: ​
4:12:11 AM:   Error location
4:12:11 AM:   In Build command from Netlify app:
4:12:11 AM:   npm run build
4:12:11 AM: ​
4:12:11 AM:   Resolved config
4:12:11 AM:   build:
4:12:11 AM:     base: /opt/build/repo/docs
4:12:11 AM:     command: npm run build
4:12:11 AM:     commandOrigin: ui
4:12:11 AM:     environment:
4:12:11 AM:       - CI
4:12:11 AM:     publish: /opt/build/repo/docs/.vitepress/dist
4:12:11 AM:     publishOrigin: ui
4:12:12 AM: Caching artifacts
4:12:12 AM: Started saving node modules
4:12:12 AM: Finished saving node modules
4:12:12 AM: Started saving build plugins
4:12:12 AM: Finished saving build plugins
4:12:12 AM: Started saving pip cache
4:12:12 AM: Finished saving pip cache
4:12:12 AM: Started saving emacs cask dependencies
4:12:12 AM: Finished saving emacs cask dependencies
4:12:12 AM: Started saving maven dependencies
4:12:12 AM: Finished saving maven dependencies
4:12:12 AM: Started saving boot dependencies
4:12:12 AM: Finished saving boot dependencies
4:12:12 AM: Started saving rust rustup cache
4:12:12 AM: Finished saving rust rustup cache
4:12:12 AM: Started saving go dependencies
4:12:14 AM: Creating deploy upload records
4:12:12 AM: Finished saving go dependencies
4:12:14 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
4:12:14 AM: Failing build: Failed to build site
4:12:14 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
4:12:14 AM: Finished processing build request in 59.909675574s
```

**Pull request merged**
