### PR TITLE
Replace dependency css-parse with css

### LINKED ISSUE #2569: Remove dep for css-parse
css-parse is a dumb package.  -> https://github.com/reworkcss/css-parse

all it does is:
`module.exports = require('css').parse;`

It hasn't been updated in 7 years, and it pulls in `css` anyway, so just pull in `css` into this library and stop using this.  This ALSO lets you move to css version 3.0.0, which fixes some old deprecations.

### PR DESCRIPTION
**Pull request by stevenjoezhang**
css-parse has not been updated for seven years
https://www.npmjs.com/package/css-parse
https://www.npmjs.com/package/css

Ref https://github.com/reworkcss/css-parse/blob/master/index.js

Issue resolved: https://github.com/stylus/stylus/issues/2569

### CODE REVIEW

**Comment by iChenLei** [comment]
Can you update this PR, Thanks.

**Comment by iChenLei** [comment]
Can you use npm 6.*  to update deps?  we will use  `"lockfileVersion": 2,` in the future, but not now. Thanks

**Comment by stevenjoezhang** [comment]
No problem, I have rebased the head branch

**Review by iChenLei — APPROVED** [review]
Nodejs v6 and newer support destructuring assignment , so LGTM

**Pull request merged**
