### PR TITLE
Extend length method to work with strings

### PR DESCRIPTION
**Pull request by iaman**
Extends the length method to allow it to check string length as well; perhaps not terribly useful, but it seems odd to have a length method that doesn't work with a basic type that has a length property.

### CODE REVIEW

**Comment by Stockbridge** [comment]
+1

**Comment by kizu** [comment]
Thanks for the PR! While this can be a useful feature, it can break someone's code due to how lists work in Stylus: someone could use the current behaviour of `length()` to check if the input is a list, expecting a single string to be `1`, for example.

While we don't have proper arrays, I'd propose to add a new bif for this, named `strlength` for example, so there won't be conflicts with the existing code.

Also, it would be nice if this bif did type coersion, so, for example, it could also accept indents and function names as input and return their string length.

**Comment by iaman** [comment]
@kizu Sounds good, I'll get hacking on it later today :)

**Comment by TerraTech** [comment]
For those that TLDR; ```length()``` was extended to support ```string``` type in release: **v0.54.6**
https://github.com/stylus/stylus/releases/tag/0.54.6

[_As an aside, it hasn't been added to the Stylus documentation as of yet._]

**Pull request merged**
